### PR TITLE
feat: New pyro+bsarch and build task support for new pyro (#109)

### PR DESCRIPTION
**Pull request by rjstone**
New feature #109 added: New version of pyro with lots of updates and also include bsarch tool along with it. Need to update the LICENSE file too.

This also rolls in #117 just to make merging easier.

Testing: Anything involving building with pyro. Also check custom tasks in tasks.json which should work as should custom pyto tasks in tasks,.jason (click the little gear on autodetected tasks). (Will add more to this later.)

To clone pr:
`git clone -b refs/pull/122/head https://github.com/joelday/papyrus-lang.git test-papyrus-vscode`

Checklist before doing the merge commit:
- [] Review code in PR
- [] Testing
- [] Check format of title for CI (make sure it has valid `<type>: <subject>` format)
- [] **Use Squash and Commit**

### CODE REVIEW

**Comment by rjstone** [comment]
i think the build only failed here due to some temporary network failure with appveyor:

```
========================================
download-compilers
========================================
An error occurred when executing task 'download-compilers'.
Error: One or more errors occurred.
	An error occurred while sending the request.
Command exited with code 1
```

**Comment by rjstone** [comment]
This now contains the official release of pyro so we should be able to merge soon (if nobody finds anything wrong).

**Comment by rjstone** [comment]
Ok, I think maybe we are finally ready to merge this. Paging @Scrivener07 to confirm....

**Comment by rjstone** [comment]
Includes license info update for #108

**Comment by Scrivener07** [comment]
Ive started to test this PR. Will report back soon.

**Comment by rjstone** [comment]
Ok, all bugs reported by scrivener fixed and pyro updated. Maybe we can finally merge. @Scrivener07

**Comment by Scrivener07** [comment]
Merged

**Pull request merged**
