### PR TITLE
docs: move default PR template to the .github meta folder

### PR DESCRIPTION
**Pull request by Scrivener07**
The last two PRs were a bust (#119, #118). Third time's the charm as they say.

### CODE REVIEW

**Comment by Scrivener07** [comment]
An interesting new GitHub service just released. 
https://github.com/marketplace?type=actions
https://help.github.com/en/actions/automating-your-workflow-with-github-actions

With the run of fumbled PRs and likely a change in the way github templates work, we will delay and further meta changes until more research is done.

**Comment by rjstone** [comment]
I didn't find anything in the new "github actions" stuff to suggest that it's replacing this templates feature as I initially thought it might be doing. 

If this last shot thing doesn't work then they must have changed something and not updated the docs. So I guess just hit the button and lets see if it works.

**Comment by rjstone** [comment]
yay it works!

**Pull request merged**
