### PR TITLE
chore: Workflow definitions for using Github Actions for CI (to replace appveyor)

### PR DESCRIPTION
**Pull request by rjstone**
This is my proposal for how to re-do the CI. I'm creating a draft pull request for the sake of discussion. **This can't just be merged without also updating keys and other security stuff** that only joel has access to do.

# Release Build/Publish: `push-master.yml`

First of all is the configuration https://github.com/rjstone/papyrus-lang/blob/workflows/.github/workflows/push-master.yml which is really just a drop-in (almost, except it would need secrets added for notifications and vsce publishing but those are done outside the config in the github ui) replacement for the appveyor build. It doesn't do anything special that isn't already done in the appveyor build, except that I added some notifications that github won't do as good of a job of by itself.

If anyone wants better/different notifications I can fix those up because I had to write my own github action (extension) to get those to work in discord anyway.

So basically nothing really changes here except you get different discord notifications from a github action instead of from appveyor. Otherwise everything builds and publishes the same way. (Even though the event says "push" it gets executed on PR merges.)

# Dev Build: `push-develop.yml`

The configuration https://github.com/rjstone/papyrus-lang/blob/workflows/.github/workflows/push-develop.yml builds all branches that are NOT master. This is primarily intended to build a 'develop' branch which if created would enable a gitflow type release process. Even if we don't do this it would still be useful for building anything but master (such as the new-parser branch etc.)

This configuration doesn't publish anything except to "build artifacts" which means you can download a VCIX package if you want, but you need to go into actions and download it from this little menu in the upper right of the page:

image

There would be a lot of these builds because this is the main check build on any branch commit or PR, so we can have downloadable packages built from these if we want to get someone to download one to test but they don't clutter up the "releases" tab in the github page. They just have to go a little "out of the way" to the Actions tab which is not difficult.

So in short this gives us our check builds and also lets us easily have VSIX packages for them available for download if needed.

# RC Build: `push-tag-rc.yml`

Finally there is https://github.com/rjstone/papyrus-lang/blob/workflows/.github/workflows/push-tag-rc.yml which does absolutely nothing unless someone pushes a tag of the form `*-rc*` such as `iss123-rc1` or similar. When it sees a tag of this form it builds the tag (which could be on any branch) the same way `push-develop.yml` does, **except that it also publishes an "RC" in the "Releases" tab like this:**

image

The main purpose of this tag is to publish pre-releases that we think are finished but still need testing without having to merge to the master branch or publish with vsce. It can be used on any branch but is primarily intended for use with the "develop" branch gitflow type workflow as described below.

# Gitflow Setup/Workflow

The gitflow type workflow would work like this:

1. Branch master into a new pre-release development branch called `develop`.
2. When preparing a new feature, branch the `develop` branch instead of `master`.
3. When someone submits a PR, it should be submitted to merge into `develop`.
4. PR is worked on until it looks feature-complete and free of totally feature-breaking bugs.
5. PR is then merged into `develop` without having to worry about it being published.
6. Possibly return to step 2 and repeat this cycle more than once with multiple PRs.
7. When develop has whatever features we want for a release, tag the develop branch with a tag like `whatever-rc1`. This causes the RC build workflow to build a "RC" and publish it in the "Releases" section of the github repo page where it's easier to see/find.
8. A PR is created to merge `develop` into `master` but the merge isn't done yet (maybe leave it as draft).
9. Ask various people to test the RC.
9. If anyone starts working on new features at this point they are kept in their topic branch and just left there until the release process is over.
10. People find bugs and bugfix PRs are created and merged into `develop`. Then another RC is tagged such as `whatever-rc2`.
11. Go to step 8 and repeat this cycle possibly but hopefully not more than 2-3 times at most.
12. Finally when everything looks good we tag `develop` with `whatever-final` (which doesn't do anything special by itself, it's just a label that this was the final RC).
13. The `develop`->`master` merge pr is squashed and merged.
14. The `push-master.yml` workflow runs as and publishes the vsix on the marketplace etc. 

# Conclusion

What we end up with looks like this in the web UI:

image

image

In Discord you see:

image

image

image

image

image

image

Checklist:
- [ ] Review code in PR
- [X] Update Secrets
- [ ] Check format of title for CI (make sure it has valid `<type>: <subject>` format)
- [ ] **Use Squash and Commit**
- [ ] branch master to develop (?)
- [ ] Disable appveyor and appveyor check actions
- [ ] Enable github actions for checks (in branch protection)

### CODE REVIEW

**Comment by joelday** [comment]
Just let me know what keys to get.

**Comment by rjstone** [comment]
Keys/secrets needed are:

- **VSCE_TOKEN** - should be put in Settings->Secrets in the github repo gui settings. (Same personal access token used by semantic-release)
- **DISCORD_WEBHOOK** - the webhook for whatever channel notifications go to. I'd recommend renaming #appveyor to #build or something then using that webhook. Webhook can be copied verbatim. Also goes in Settings->Secrets for the repo.
- GITHUB_TOKEN - no action is needed on this. It's "built in" to the github workflows execution environment.

Examples of where/how they are used:

```
    - name: Semantic Release
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
      uses: ecampidoglio/cake-action@v1.1.1
      with:
        target: npm-semantic-release
```

(secrets is a context that picks up the GUI configured secrets)

```
    - name: Notify Success
      if: success()
      uses: rjstone/discord-webhook-notify@v1
      with:
        severity: info
        description: '**Build Succeeded!** ${{ github.ref }} https://github.com/joelday/papyrus-lang/actions'
        footer: Build Ended (Success)
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
```

(For security reasons you have to explicitly pass these to actions like this.... Actions can't automatically just access all secrets so if I wanted to steal someone's other secrets using `rjstone/discord-webhook-notify` I wouldn't be able to. Best anyone could do like that would be steal someone's discord webhook.)

**Comment by joelday** [comment]
Added the secrets.

**Comment by rjstone** [comment]
Ok! I will ask Scrivener to review and merge.

**Pull request merged**
